# Generated by Django 5.0.1 on 2024-02-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_comment',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='date_liked',
            new_name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/blog/images/'),
        ),
    ]
