# Generated by Django 5.0 on 2024-01-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_subscriber_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='recurrent_type',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionRecurrentType',
        ),
        migrations.DeleteModel(
            name='SubscriptionType',
        ),
    ]
