# Generated by Django 5.0 on 2023-12-29 00:48

import users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
    ]
