# Generated by Django 5.0 on 2024-01-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_subscriptiontype_recurrent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='work_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
