# Generated by Django 5.0 on 2023-12-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_facilitator',
            field=models.BooleanField(default=False),
        ),
    ]
