# Generated by Django 5.0 on 2024-01-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_gender_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
