# Generated by Django 5.0 on 2024-01-04 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_gender_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='logo',
            new_name='image',
        ),
    ]
