# Generated by Django 5.0 on 2023-12-29 07:01

import users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
    ]
