# Generated by Django 5.0.1 on 2024-01-11 01:34

import authAPI.manager
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitator',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='organizationregisterergender',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='organizationregisterergender',
            name='organization',
        ),
        migrations.AlterField(
            model_name='organization',
            name='registerer_gender',
            field=models.CharField(default='Male', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='useracademiclevel',
            name='academic_level',
        ),
        migrations.RemoveField(
            model_name='useracademiclevel',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='usergender',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='usergender',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='facilitator',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='facilitator',
            managers=[
                ('objects', authAPI.manager.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_job_field',
            new_name='current_work_field',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='desired_job_field',
            new_name='desired_work_field',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='city',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='country',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='image',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='username',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_photo',
        ),
        migrations.AddField(
            model_name='facilitator',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_organization', to='authAPI.partnerorganization'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='registerer_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='contact_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='contact_phone',
            field=models.CharField(default=12345678, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(default='Single', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=12345678, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Lagos', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/facilitators/'),
        ),
        migrations.DeleteModel(
            name='FacilitatorGender',
        ),
        migrations.DeleteModel(
            name='OrganizationRegistererGender',
        ),
        migrations.DeleteModel(
            name='UserAcademicLevel',
        ),
        migrations.DeleteModel(
            name='UserGender',
        ),
    ]
