# Generated by Django 5.0.1 on 2024-01-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_remove_facilitator_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AddField(
            model_name='facilitator',
            name='bio',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='field',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitator',
            name='years_of_experience',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='partner_organization',
            field=models.CharField(default='TruuSkill', max_length=150),
            preserve_default=False,
        ),
    ]
