# Generated by Django 5.0.1 on 2024-01-24 20:20

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0004_alter_facilitator_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitator',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='PartnerOrganization',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='registerer_email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_name',
            new_name='contact_job_title',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='registerer_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='registerer_phone_number',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='registerer_job_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_job',
            new_name='current_job_title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='desired_job',
            new_name='desired_job_title',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_age',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_country',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_gender',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_state',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registerer_zip',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_facilitator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authAPI.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authAPI.organizationtype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_level',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authAPI.academiclevel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Facilitator',
        ),
        migrations.DeleteModel(
            name='OrganizationUser',
        ),
    ]
