# Generated by Django 5.0.1 on 2024-01-24 20:34

import authAPI.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0006_remove_user_academic_level_user_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authAPI.manager.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
