# Generated by Django 5.0.1 on 2024-01-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0007_alter_user_managers_alter_user_years_of_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='academic_year',
            new_name='academic_level',
        ),
    ]
