# Generated by Django 5.0.1 on 2024-01-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0008_rename_academic_year_user_academic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiclevel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
