# Generated by Django 5.0.1 on 2024-02-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0011_alter_user_image_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
