# Generated by Django 5.0.1 on 2024-02-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0012_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
