# Generated by Django 5.0.1 on 2024-02-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0013_alter_organization_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_facilitator',
        ),
    ]
