# Generated by Django 5.0.1 on 2024-02-07 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0014_remove_user_is_facilitator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='facilitator_details', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_facilitator', models.BooleanField(default=True)),
                ('date_upgraded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
