# Generated by Django 5.0.1 on 2024-02-07 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0016_alter_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_job_title',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
