# Generated by Django 5.0.1 on 2024-02-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0018_remove_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact',
        ),
    ]
