# Generated by Django 5.0.1 on 2024-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0019_remove_organization_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(default='a@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_job_title',
            field=models.CharField(default='owner', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_name',
            field=models.CharField(default='john doe', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(default='1234', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
