# Generated by Django 5.0.1 on 2024-02-07 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0020_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_job_title',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='authAPI.organization'),
        ),
    ]
