# Generated by Django 5.0.1 on 2024-02-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0021_remove_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
    ]
