# Generated by Django 5.0.1 on 2024-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0022_remove_organization_contact_remove_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
