# Generated by Django 5.0.1 on 2024-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0024_organization_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
