# Generated by Django 5.0.1 on 2024-01-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0004_rename_facilitator_course_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
