# Generated by Django 5.0.1 on 2024-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0007_alter_field_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='specialization_courses', to='courseAPI.course'),
        ),
    ]
