# Generated by Django 5.0.1 on 2024-01-25 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0010_alter_course_is_active_alter_course_language_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Lesson',
        ),
        migrations.RemoveField(
            model_name='specializationcourse',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='specializationcourse',
            name='course',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='module',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='module',
        ),
        migrations.RemoveField(
            model_name='image',
            name='module',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='module',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='module',
        ),
        migrations.AddField(
            model_name='audio',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.lesson'),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='course_lessons', to='courseAPI.lesson'),
        ),
        migrations.AddField(
            model_name='image',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.lesson'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.lesson'),
        ),
        migrations.AddField(
            model_name='reading',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.lesson'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='courseAPI.question'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('objective', models.TextField()),
                ('skills', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='programme_courses', to='courseAPI.course')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseAPI.field')),
            ],
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='SpecializationCourse',
        ),
    ]
