# Generated by Django 5.0.1 on 2024-01-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0011_rename_module_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='objective',
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
