# Generated by Django 5.0.1 on 2024-01-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0012_remove_programme_objective_course_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excerpt',
            field=models.TextField(default='This course will prepare you with the skills neccessary to grow in your desired field of study'),
            preserve_default=False,
        ),
    ]
