# Generated by Django 5.0.1 on 2024-02-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0015_alter_courselevel_options_remove_course_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='specialization_courses', to='courseAPI.course'),
        ),
    ]
