# Generated by Django 5.0.1 on 2024-02-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0017_alter_course_options_course_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursefacilitator',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialization',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specializationcourse',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.URLField(auto_created=True, default='/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='specialization_courses', to='courseAPI.course'),
        ),
    ]
