# Generated by Django 5.0.1 on 2024-02-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0018_answer_link_audio_link_course_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
