# Generated by Django 5.0.1 on 2024-02-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0021_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(auto_created=True, blank=True, null=True),
        ),
    ]
