# Generated by Django 5.0.1 on 2024-02-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0022_alter_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
    ]
