# Generated by Django 5.0.1 on 2024-02-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0024_alter_course_facilitators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='link',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='link',
        ),
        migrations.RemoveField(
            model_name='coursefacilitator',
            name='link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='link',
        ),
        migrations.RemoveField(
            model_name='question',
            name='link',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='link',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='link',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
    ]
