# Generated by Django 5.0.1 on 2024-02-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0027_alter_audio_audio_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='specialization_courses', to='courseAPI.course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(),
        ),
    ]
