# Generated by Django 5.0.1 on 2024-02-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0030_course_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
