# Generated by Django 5.0.1 on 2024-02-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0031_remove_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseAPI.course'),
            preserve_default=False,
        ),
    ]
