# Generated by Django 5.0.1 on 2024-02-06 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0034_lesson_time_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('link', models.URLField(blank=True, max_length=5000, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('time_duration', models.IntegerField()),
                ('date_due', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coursefacilitator',
            name='facilitator',
        ),
        migrations.AddField(
            model_name='answer',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='class_interval',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursefacilitator',
            name='facilitators',
            field=models.ManyToManyField(related_name='facilitators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_link1', models.URLField(max_length=5000)),
                ('class_link2', models.URLField(blank=True, max_length=5000, null=True)),
                ('class_number', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('objectives', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('time_duration', models.IntegerField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('class_did_hold', models.BooleanField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseAPI.course')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.class'),
        ),
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(related_name='course_classes', to='courseAPI.class'),
        ),
        migrations.AddField(
            model_name='image',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.class'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='the_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.class'),
        ),
        migrations.AddField(
            model_name='reading',
            name='the_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.class'),
        ),
        migrations.AddField(
            model_name='video',
            name='the_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseAPI.class'),
        ),
        migrations.CreateModel(
            name='FacilitatorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator', to=settings.AUTH_USER_MODEL)),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_class_facilitated', to='courseAPI.class')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=5000)),
                ('date', models.DateField(auto_now=True)),
                ('assessments', models.ManyToManyField(related_name='assignments_for_class', to='courseAPI.assessment')),
                ('audios', models.ManyToManyField(related_name='audios_for_class', to='courseAPI.audio')),
                ('images', models.ManyToManyField(related_name='images_for_class', to='courseAPI.image')),
                ('readings', models.ManyToManyField(related_name='readings_for_class', to='courseAPI.reading')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_for_class', to='courseAPI.class')),
                ('videos', models.ManyToManyField(related_name='videos_for_class', to='courseAPI.video')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_attend_class', models.BooleanField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_class_student_attended', to='courseAPI.class')),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_class', to='courseAPI.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Classes',
            },
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='UserLesson',
        ),
    ]
