# Generated by Django 5.0.1 on 2024-02-06 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0035_assessment_remove_userlesson_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilitatorattendance',
            unique_together={('facilitator', 'the_class')},
        ),
        migrations.AlterUniqueTogether(
            name='specializationcourse',
            unique_together={('specialization', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='userclass',
            unique_together={('the_class', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
    ]
