# Generated by Django 5.0.1 on 2024-02-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0037_course_welcome_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
