# Generated by Django 5.0.1 on 2024-02-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0015_facilitator'),
        ('courseAPI', '0038_course_intro_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='facilitators',
            field=models.ManyToManyField(to='authAPI.facilitator'),
        ),
        migrations.AlterField(
            model_name='coursefacilitator',
            name='facilitators',
            field=models.ManyToManyField(related_name='facilitators', to='authAPI.facilitator'),
        ),
        migrations.AlterField(
            model_name='facilitatorattendance',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator', to='authAPI.facilitator'),
        ),
    ]
