# Generated by Django 5.0.1 on 2024-02-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0039_course_facilitators_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
