# Generated by Django 5.0.1 on 2024-02-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0040_alter_class_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classes',
        ),
    ]
