# Generated by Django 5.0.1 on 2024-02-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0041_remove_course_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='community_link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='community_link2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
