# Generated by Django 5.0.1 on 2024-02-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0042_course_community_link1_course_community_link2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='the_class',
        ),
        migrations.AddField(
            model_name='class',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_for_class', to='courseAPI.resource'),
        ),
    ]
