# Generated by Django 5.0.1 on 2024-02-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0024_organization_contact'),
        ('courseAPI', '0044_alter_quiz_options_assessment_the_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='facilitators',
        ),
        migrations.AddField(
            model_name='class',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authAPI.facilitator'),
        ),
    ]
