# Generated by Django 5.0.1 on 2024-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0046_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
