# Generated by Django 5.0.1 on 2024-03-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0047_course_image_link_alter_course_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='courses',
        ),
        migrations.AddField(
            model_name='specialization',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
