# Generated by Django 5.0.1 on 2024-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0048_remove_specialization_courses_specialization_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='image_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='next_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='price',
            field=models.DecimalField(decimal_places=2, default=250000, max_digits=9),
            preserve_default=False,
        ),
    ]
