# Generated by Django 5.0.1 on 2024-03-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0049_specialization_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='duration',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
