# Generated by Django 5.0.1 on 2024-03-09 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0050_specialization_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_level', to='courseAPI.courselevel'),
        ),
    ]
