# Generated by Django 5.0.1 on 2024-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0052_alter_specializationcourse_specialization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specializationcourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='specializationcourse',
            name='courses',
            field=models.ManyToManyField(related_name='specialization_courses', to='courseAPI.course'),
        ),
        migrations.RemoveField(
            model_name='specializationcourse',
            name='course',
        ),
    ]
