# Generated by Django 5.0.1 on 2024-03-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0057_alter_course_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specializationcourse',
            name='courses',
        ),
        migrations.AddField(
            model_name='specializationcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialization_course', to='courseAPI.course'),
        ),
    ]
