# Generated by Django 5.0 on 2024-01-02 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRecurrentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('time_period', models.BigIntegerField()),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.SlugField(max_length=1000)),
                ('active', models.BooleanField(default=False)),
                ('recurrent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptionAPI.subscriptionrecurrenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_subscription', models.DateField()),
                ('subscription_renewal_date', models.DateField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subscriptionAPI.subscriptiontype')),
            ],
        ),
    ]
