# Generated by Django 5.0 on 2024-01-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionAPI', '0002_remove_subscriptiontype_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrecurrenttype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
