# Generated by Django 5.0.1 on 2024-02-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url_name', models.CharField(max_length=200, verbose_name='url_name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='FooterTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('footer_links', models.ManyToManyField(related_name='footer_links', to='web.footerlink', verbose_name='footer_links')),
            ],
        ),
    ]
