# Generated by Django 5.0.1 on 2024-02-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_footerlink_footertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
