# Generated by Django 5.0.1 on 2024-02-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0029_alter_course_skills_alter_course_tags'),
        ('web', '0006_remove_coursecarousel_courses_carouselcoursel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselCoursel',
            new_name='CarouselCourse',
        ),
    ]
