# Generated by Django 5.0.1 on 2024-02-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0029_alter_course_skills_alter_course_tags'),
        ('web', '0007_rename_carouselcoursel_carouselcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecarousel',
            name='courses',
            field=models.ManyToManyField(to='courseAPI.course'),
        ),
        migrations.DeleteModel(
            name='CarouselCourse',
        ),
    ]
