# Generated by Django 5.0.1 on 2024-02-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_coursecarousel_courses_delete_carouselcourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessModel',
            new_name='StaticPage',
        ),
    ]
