# Generated by Django 5.0.1 on 2024-02-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_businessmodel_staticpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticpage',
            old_name='description',
            new_name='content',
        ),
    ]
