# Generated by Django 5.0.1 on 2024-02-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_description_staticpage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('footer_links', models.ManyToManyField(related_name='static_pages', to='web.staticpage', verbose_name='static_pages')),
            ],
        ),
        migrations.DeleteModel(
            name='FooterTitle',
        ),
    ]
