# Generated by Django 5.0.1 on 2024-02-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_description_staticpage_content'),
    ]

    operations = [
        
    ]
