# Generated by Django 5.0.1 on 2024-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_footernav_delete_footertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='is_model_page',
            field=models.BooleanField(default=False),
        ),
    ]
