# Generated by Django 5.0.1 on 2024-02-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderAPI', '0005_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpurchase',
            options={'get_latest_by': 'date_added', 'ordering': ('date_added',), 'verbose_name': 'User Purchase', 'verbose_name_plural': 'User Purchases'},
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
