# Generated by Django 5.0.1 on 2024-03-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderAPI', '0008_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
