# Generated by Django 5.0.1 on 2024-01-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilsAPI', '0003_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='message',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='gender',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
