# Generated by Django 5.0.1 on 2024-02-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilsAPI', '0009_note_note_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_number',
        ),
    ]
