# Generated by Django 5.0.1 on 2024-02-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0045_remove_course_facilitators_class_facilitator'),
        ('utilsAPI', '0010_remove_note_note_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseAPI.class'),
        ),
    ]
