# Generated by Django 5.0.1 on 2024-02-20 02:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0047_course_image_link_alter_course_skills'),
        ('utilsAPI', '0012_remove_favourite_courses_favourite_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'course')},
        ),
    ]
