# Generated by Django 5.0.1 on 2024-02-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilsAPI', '0014_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
