# Generated by Django 5.0.1 on 2024-02-29 04:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAPI', '0047_course_image_link_alter_course_skills'),
        ('utilsAPI', '0015_alter_review_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'course')},
        ),
    ]
